### ISSUE TITLE
Do not work on Xcode7.2

### ISSUE THREAD

**Issue by superleexpert** [fortinmike/XcodeBoost#45]
I installed the XcodeBoost already on Xcode7.2. And set the "Manually:" steps already. 
But all the function are bad. Can anybody help me?

**Comment by superleexpert** [comment]
By the way, the highlights search is OK.

**Comment by fortinmike** [comment]
Hi there,

"Does not work" does not tell me much. What symptoms are you observing exactly?

Did you try triggering the features through their menu items or only with keyboard shortcuts? Maybe your shortcuts are configured incorrectly.

**Comment by superleexpert** [comment]
Hi fortinmike,

I have checked the shortcuts correctly.

I suspect that the cause of other plugins, but i have not found reason.

Thanks.

**Comment by fortinmike** [comment]
Oh I see. I'll close this until you can provide some more info. Maybe posting a more specific issue (with detailed reproduction steps) would be best. See these guidelines for general guidance : https://sourceware.org/bugzilla/page.cgi?id=bug-writing.html
