### ISSUE TITLE
Does this also work with C++ / Is planned to support C++?

### ISSUE THREAD

**Issue by FramusRock** [fortinmike/XcodeBoost#46]
This would be highly appreciated ;)

**Comment by fortinmike** [comment]
Unfortunately I have no plans to add C++ support to XcodeBoost at the moment; Swift support is much higher on the priority list.

I would probably accept a pull request, but the current design is not well suited to supporting additional languages, so I'm not sure adding on top of the current stack would be appropriate.

I was thinking of implementing a new architecture on top of LLVM/Clang to provide Swift support and more robust/complex refactorings &mdash; which might also enable better support of Obj-C and possibly C++ &mdash; but I haven't gotten to it yet.

**Comment by FramusRock** [comment]
Okay, I see that's a pity.

I was using your tools for Objective-C and was hoping that these brilliant improvements were also applicable to C++, which I got to code in now ;)

Do you by any means know any other Xcode plugins that improve coding in C++?

**Comment by fortinmike** [comment]
I do not know of any Xcode plugin that offers "pseudo-refactorings" for C++ like XcodeBoost does for Objective-C.

However, if you like XcodeBoost and would like a powerful complement to Xcode for heavy code refactoring and inspection, I suggest that you take a look at the JetBrains IDEs, specifically [AppCode](https://www.jetbrains.com/objc/?fromMenu) (for iOS and Mac app development, including C++ support) and [CLion](https://www.jetbrains.com/clion/?fromMenu) (for cross-platform C++).

JetBrains tools rock for those kinds of things and were a big inspiration for XcodeBoost.
